apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: app1-tgb
  namespace: sim-demo
spec:
  serviceRef:
    name: app1
    port: 80
  targetGroupARN: arn:aws:elasticloadbalancing:us-east-1:185542568106:targetgroup/sim-demo-grpc-tg/42f47c516aafeae4
  targetType: ip
